[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173  # Vite's default port

[build.environment]
  NODE_VERSION = "20"  # Using Node.js 20 LTS

# Redirects all traffic to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
